using System.Globalization;
using System.Net;
using System.Text;
using System.Text.RegularExpressions;
using Matmon.Core.Domain;
using Matmon.Core.Sample;
using Matmon.Host.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.DependencyInjection;
using Matmon.Host.Ui;

namespace Matmon.Host.Pages;

public sealed class CreateProbeInput
{
    public string Name { get; set; } = string.Empty;

    public string? Description { get; set; }

    public Guid? ParentId { get; set; }
}

public sealed class CreateFolderInput
{
    public string Name { get; set; } = string.Empty;

    public string? Description { get; set; }

    public Guid? ParentId { get; set; }
}

public sealed class CreateHostInput
{
    public string Name { get; set; } = string.Empty;

    public string Address { get; set; } = string.Empty;

    public string? Description { get; set; }

    public Guid? ParentId { get; set; }
}

/// <summary>
/// Shared shape consumed by the reusable sensor-editor partials (Shared/_Sensor*.cshtml)
/// so the create, element-edit and template-edit pages render the same markup from one
/// source. Implemented by CreateSensorInput, WorkspaceElementEditorInput and
/// WorkspaceTemplateEditorInput.
/// </summary>
public interface ISensorThresholdEditor
{
    SensorChannelMode SensorChannelMode { get; }

    int SensorChannelThresholdVisibleCount { get; }

    List<WorkspaceSensorChannelThresholdFieldInput> SensorChannelThresholdFields { get; }
}

/// <summary>Shared binding surface for the reusable <c>_SensorParameters</c> editor partial.</summary>
public interface ISensorParameterEditor
{
    string? SensorTypeKey { get; }

    List<WorkspaceSensorParameterFieldInput> SensorParameterFields { get; set; }

    string SensorAdvancedParametersText { get; set; }
}

/// <summary>Shared binding surface for the reusable <c>_SensorCredentials</c> editor partial.</summary>
public interface ISensorCredentialEditor
{
    List<WorkspaceSensorParameterFieldInput> SensorParameterFields { get; set; }

    List<SelectListItem> CredentialOptions { get; set; }

    Guid? SelectedCredentialId { get; set; }
}

/// <summary>Shared binding surface for the reusable <c>_SensorSchedule</c> editor partial.</summary>
public interface ISensorScheduleEditor
{
    /// <summary>Schedule mode: inherit | every | daily | weekly | monthly.</summary>
    string SchedulePreset { get; set; }

    /// <summary>For "every": the interval value expressed in <see cref="ScheduleEveryUnit"/>.</summary>
    int? ScheduleEveryValue { get; set; }

    /// <summary>For "every": seconds | minutes | hours | days.</summary>
    string ScheduleEveryUnit { get; set; }

    DayOfWeek? ScheduleDayOfWeek { get; set; }

    /// <summary>Weekly schedule weekdays (multi-select), e.g. Monday + Thursday.</summary>
    List<DayOfWeek> ScheduleDaysOfWeek { get; set; }

    int? ScheduleDayOfMonth { get; set; }

    string? ScheduleTime { get; set; }

    string? ScheduleInheritedLabel { get; set; }
}

public sealed class CreateSensorInput : ISensorThresholdEditor, ISensorScheduleEditor, ISensorParameterEditor, ISensorCredentialEditor
{
    public string Name { get; set; } = string.Empty;

    public bool NameAutoGenerated { get; set; } = true;

    public string SensorTypeKey { get; set; } = "ping";

    public Guid? TemplateId { get; set; }

    public List<SelectListItem> TemplateOptions { get; set; } = [];

    public string Target { get; set; } = string.Empty;

    public string? TargetPlaceholder { get; set; }

    public string? Description { get; set; }

    public string? TagsText { get; set; }

    public Guid? ParentId { get; set; }

    public bool? Highlight { get; set; }

    public string? HighlightInheritedLabel { get; set; }

    public string SchedulePreset { get; set; } = "inherit";

    public int? ScheduleEveryValue { get; set; }

    public string ScheduleEveryUnit { get; set; } = "minutes";

    public DayOfWeek? ScheduleDayOfWeek { get; set; } = DayOfWeek.Monday;

    public List<DayOfWeek> ScheduleDaysOfWeek { get; set; } = [];

    public int? ScheduleDayOfMonth { get; set; } = 1;

    public string? ScheduleTime { get; set; }

    public string? ScheduleInheritedLabel { get; set; }

    public Guid? SelectedCredentialId { get; set; }

    public List<SelectListItem> CredentialOptions { get; set; } = [];

    public List<WorkspaceSensorParameterFieldInput> SensorParameterFields { get; set; } = [];

    public string SensorAdvancedParametersText { get; set; } = string.Empty;

    public string SnmpWalkRootOid { get; set; } = "1.3.6.1.2.1";

    public List<WorkspaceSnmpWalkItemInput> SnmpWalkItems { get; set; } = [];

    public List<WorkspaceSensorChannelThresholdFieldInput> SensorChannelThresholdFields { get; set; } = [];

    public int SensorChannelThresholdVisibleCount { get; set; }

    public SensorChannelMode SensorChannelMode { get; set; } = SensorChannelMode.Dynamic;
}

public sealed class CreateTemplateInput
{
    public string Name { get; set; } = string.Empty;

    public MonitoringTemplateScope TargetKind { get; set; } = MonitoringTemplateScope.Any;

    public string SensorTypeKey { get; set; } = PingSensorExecutor.Definition.Key;

    public Guid? ParentTemplateId { get; set; }
}

public sealed class CreateNotificationRuleInput
{
    public string Name { get; set; } = string.Empty;

    public bool Enabled { get; set; } = true;

    public Guid? SenderId { get; set; }

    public Guid? ReceiverId { get; set; }

    public Guid? TargetElementId { get; set; }

    public bool IncludeDescendants { get; set; } = true;

    public List<SensorState> TriggerStates { get; set; } = [];

    public int? CooldownMinutes { get; set; } = 15;

    public int? Threshold { get; set; } = 5;

    public string SubjectTemplate { get; set; } = NotificationTemplateCatalog.DefaultSubjectTemplate;

    public string TextTemplate { get; set; } = NotificationTemplateCatalog.DefaultTextTemplate;

    public string HtmlTemplate { get; set; } = NotificationTemplateCatalog.DefaultHtmlTemplate;

    public List<SelectListItem> SenderOptions { get; set; } = [];

    public List<SelectListItem> ReceiverOptions { get; set; } = [];

    public List<SelectListItem> TargetOptions { get; set; } = [];

    public List<SelectListItem> TriggerStateOptions { get; set; } = [];
}

public class CreateNotificationSenderInput
{
    public string Name { get; set; } = string.Empty;

    public bool Enabled { get; set; } = true;

    public NotificationEndpointKind Kind { get; set; } = NotificationEndpointKind.Email;

    public string SenderName { get; set; } = "Matmon";

    public string SenderEmail { get; set; } = "matmon@example.local";

    public string SmtpHost { get; set; } = "smtp.example.local";

    public int? SmtpPort { get; set; } = 587;

    public bool UseSsl { get; set; } = true;

    public string? Username { get; set; }

    public string? Password { get; set; }

    public string EndpointUrl { get; set; } = string.Empty;

    public string? Secret { get; set; }

    public int? TimeoutSeconds { get; set; } = 10;
}

public sealed class WorkspaceNotificationSenderEditorInput : CreateNotificationSenderInput
{
    public Guid Id { get; set; }
}

public class CreateNotificationReceiverInput
{
    public string Name { get; set; } = string.Empty;

    public bool Enabled { get; set; } = true;

    public NotificationEndpointKind Kind { get; set; } = NotificationEndpointKind.Email;

    public string Target { get; set; } = string.Empty;

    public string? Secret { get; set; }

    public int? TimeoutSeconds { get; set; } = 10;
}

public sealed class WorkspaceNotificationReceiverEditorInput : CreateNotificationReceiverInput
{
    public Guid Id { get; set; }
}

public sealed class WorkspaceElementEditorInput : ISensorThresholdEditor, ISensorScheduleEditor, ISensorParameterEditor, ISensorCredentialEditor
{
    public Guid Id { get; set; }

    public string Kind { get; set; } = string.Empty;

    public string Name { get; set; } = string.Empty;

    public string? Description { get; set; }

    public string? TagsText { get; set; }

    public Guid? ParentId { get; set; }

    public string? ProbeId { get; set; }

    public string? EnrollmentToken { get; set; }

    public string? ProbeSubnetsText { get; set; }

    public string? Address { get; set; }

    public string? SensorTypeKey { get; set; }

    public string? Target { get; set; }

    public string? TargetPlaceholder { get; set; }

    public bool? Highlight { get; set; }

    public string? HighlightInheritedLabel { get; set; }

    public bool IsPaused { get; set; }

    public string SchedulePreset { get; set; } = "inherit";

    public int? ScheduleEveryValue { get; set; }

    public string ScheduleEveryUnit { get; set; } = "minutes";

    public DayOfWeek? ScheduleDayOfWeek { get; set; } = DayOfWeek.Monday;

    public List<DayOfWeek> ScheduleDaysOfWeek { get; set; } = [];

    public int? ScheduleDayOfMonth { get; set; } = 1;

    public string? ScheduleTime { get; set; }

    public string? ScheduleInheritedLabel { get; set; }

    public string EnabledMode { get; set; } = "inherit";

    public string? EnabledInheritedLabel { get; set; }

    public int? PollingIntervalSeconds { get; set; }

    public string? PollingIntervalSecondsPlaceholder { get; set; }

    public int? TimeoutSeconds { get; set; }

    public string? TimeoutSecondsPlaceholder { get; set; }

    public int? RetryCount { get; set; }

    public string? RetryCountPlaceholder { get; set; }

    public int? EventRetentionDays { get; set; }

    public string? EventRetentionDaysPlaceholder { get; set; }

    public int? ObservationRetentionDays { get; set; }

    public string? ObservationRetentionDaysPlaceholder { get; set; }

    public int? StatisticsRetentionDays { get; set; }

    public string? StatisticsRetentionDaysPlaceholder { get; set; }

    public int? StatisticsBucketMinutes { get; set; }

    public string? StatisticsBucketMinutesPlaceholder { get; set; }

    /// <summary>Optional fixed graph y-axis bounds (sensor native unit); null = auto-scale.</summary>
    public double? GraphMinValue { get; set; }

    public double? GraphMaxValue { get; set; }

    /// <summary>Human-readable per-sensor-type telemetry defaults (null for non-sensors).</summary>
    public string? TelemetryProfileSummary { get; set; }

    public string ParametersText { get; set; } = string.Empty;

    public string? ParametersTextPlaceholder { get; set; }

    public string SensorAdvancedParametersText { get; set; } = string.Empty;

    public string ThresholdsText { get; set; } = string.Empty;

    public string? ThresholdsTextPlaceholder { get; set; }

    public List<WorkspaceSensorChannelThresholdFieldInput> SensorChannelThresholdFields { get; set; } = [];

    public int SensorChannelThresholdVisibleCount { get; set; }

    public SensorChannelMode SensorChannelMode { get; set; } = SensorChannelMode.Dynamic;

    public List<Guid> AppliedTemplateIds { get; set; } = [];

    public Guid? TemplateOriginId { get; set; }

    public string? TemplateOriginName { get; set; }

    public List<SelectListItem> ParentOptions { get; set; } = [];

    public List<SelectListItem> TemplateOptions { get; set; } = [];

    public List<SelectListItem> SensorTypeOptions { get; set; } = [];

    public List<SelectListItem> CredentialOptions { get; set; } = [];

    public string? BootstrapSnippet { get; set; }

    public List<WorkspaceSensorParameterFieldInput> SensorParameterFields { get; set; } = [];

    public List<WorkspaceCredentialBundleInput> CredentialBundles { get; set; } = [];

    public int CredentialBundleVisibleCount { get; set; }

    public Guid? SelectedCredentialId { get; set; }
}

public sealed class WorkspaceSensorParameterFieldInput
{
    public string Key { get; set; } = string.Empty;

    public string Label { get; set; } = string.Empty;

    public string? Group { get; set; }

    public SensorParameterKind Kind { get; set; } = SensorParameterKind.Text;

    public string? Description { get; set; }

    public bool Required { get; set; }

    public string? Placeholder { get; set; }

    public string? DisplayPlaceholder { get; set; }

    public string? InheritedValue { get; set; }

    public string? EffectiveValue { get; set; }

    public int? Min { get; set; }

    public int? Max { get; set; }

    public string? Step { get; set; }

    public string? Value { get; set; }

    public MonitoringCredentialKind? CredentialKind { get; set; }

    public bool IsCredential => CredentialKind is not null;

    public string? VisibleWhenParameterKey { get; set; }

    public string VisibleWhenValuesText { get; set; } = string.Empty;

    public bool IsVisible { get; set; } = true;

    public List<SelectListItem> Options { get; set; } = [];
}

public sealed class WorkspaceSensorChannelThresholdFieldInput
{
    public string ChannelKey { get; set; } = string.Empty;

    public string ChannelLabel { get; set; } = string.Empty;

    public string? Unit { get; set; }

    public bool IsDefault { get; set; }

    public string WarningComparison { get; set; } = ">";

    public string WarningValue { get; set; } = string.Empty;

    public string? WarningValuePlaceholder { get; set; }

    public string CriticalComparison { get; set; } = ">";

    public string CriticalValue { get; set; } = string.Empty;

    public string? CriticalValuePlaceholder { get; set; }

    public string Visual { get; set; } = "auto";

    /// <summary>Whether this channel is recorded into long-term statistics.</summary>
    public bool Logged { get; set; } = true;

    /// <summary>The channel's own default logging state (posted hidden), so the save only stores an override when it differs.</summary>
    public bool LogByDefault { get; set; } = true;

    /// <summary>A virtual/derived channel (e.g. <c>sensorState</c>): no user thresholds, but it can be picked as the default channel and given a visual.</summary>
    public bool IsVirtual { get; set; }

    /// <summary>Display-only: the channel has stored config (thresholds/visual/logging) but is no longer
    /// reported by the sensor's latest run. Rendered as "no longer reported" so it isn't mistaken for a live channel.</summary>
    public bool IsOrphaned { get; set; }

    public bool IsDeleted { get; set; }
}

public sealed class WorkspaceSnmpWalkItemInput
{
    public bool Selected { get; set; }

    public string Oid { get; set; } = string.Empty;

    public string Syntax { get; set; } = string.Empty;

    public string Value { get; set; } = string.Empty;

    public bool IsNumeric { get; set; }
}

public sealed class WorkspaceTemplateEditorInput : ISensorThresholdEditor, ISensorScheduleEditor, ISensorParameterEditor
{
    public Guid Id { get; set; }

    public string Name { get; set; } = string.Empty;

    public string? TagsText { get; set; }

    public MonitoringTemplateScope TargetKind { get; set; } = MonitoringTemplateScope.Any;

    public string SensorTypeKey { get; set; } = PingSensorExecutor.Definition.Key;

    public List<WorkspaceSensorParameterFieldInput> SensorParameterFields { get; set; } = [];

    public string SensorAdvancedParametersText { get; set; } = string.Empty;

    public Guid? ParentTemplateId { get; set; }

    public string EnabledMode { get; set; } = "inherit";

    public int? PollingIntervalSeconds { get; set; }

    public int? TimeoutSeconds { get; set; }

    public int? RetryCount { get; set; }

    public int? EventRetentionDays { get; set; }

    public int? ObservationRetentionDays { get; set; }

    public int? StatisticsRetentionDays { get; set; }

    public int? StatisticsBucketMinutes { get; set; }

    public string ParametersText { get; set; } = string.Empty;

    public string ThresholdsText { get; set; } = string.Empty;

    public bool? Highlight { get; set; }

    public string? HighlightInheritedLabel { get; set; }

    public string SchedulePreset { get; set; } = "inherit";

    public int? ScheduleEveryValue { get; set; }

    public string ScheduleEveryUnit { get; set; } = "minutes";

    public DayOfWeek? ScheduleDayOfWeek { get; set; } = DayOfWeek.Monday;

    public List<DayOfWeek> ScheduleDaysOfWeek { get; set; } = [];

    public int? ScheduleDayOfMonth { get; set; } = 1;

    public string? ScheduleTime { get; set; }

    public string? ScheduleInheritedLabel { get; set; }

    public List<WorkspaceSensorChannelThresholdFieldInput> SensorChannelThresholdFields { get; set; } = [];

    public int SensorChannelThresholdVisibleCount { get; set; }

    public SensorChannelMode SensorChannelMode { get; set; } = SensorChannelMode.Dynamic;

    public List<SelectListItem> ParentOptions { get; set; } = [];

    public string? EnabledInheritedLabel { get; set; }

    public string? PollingIntervalSecondsPlaceholder { get; set; }

    public string? TimeoutSecondsPlaceholder { get; set; }

    public string? RetryCountPlaceholder { get; set; }

    public string? EventRetentionDaysPlaceholder { get; set; }

    public string? ObservationRetentionDaysPlaceholder { get; set; }

    public string? StatisticsRetentionDaysPlaceholder { get; set; }

    public string? StatisticsBucketMinutesPlaceholder { get; set; }

    public string? ParametersTextPlaceholder { get; set; }

    public string? ThresholdsTextPlaceholder { get; set; }

    public List<SelectListItem> CredentialOptions { get; set; } = [];

    public List<WorkspaceCredentialBundleInput> CredentialBundles { get; set; } = [];

    public int CredentialBundleVisibleCount { get; set; }

    public Guid? SelectedCredentialId { get; set; }

    public IReadOnlyList<TemplateImpactRow> ImpactRows { get; set; } = [];
}

public sealed class WorkspaceCredentialBundleInput
{
    public Guid Id { get; set; }

    public string Name { get; set; } = string.Empty;

    public MonitoringCredentialKind Kind { get; set; } = MonitoringCredentialKind.Generic;

    public string? Description { get; set; }

    public string? WinrmUsername { get; set; }

    public string? WinrmPassword { get; set; }

    public string? SshUsername { get; set; }

    public string? SshPassword { get; set; }

    public string? SshPrivateKeyPath { get; set; }

    public string? PveUser { get; set; }

    public string? PveTokenId { get; set; }

    public string? PveTokenSecret { get; set; }

    public string? MssqlUsername { get; set; }

    public string? MssqlPassword { get; set; }

    public string? SnmpCommunity { get; set; }

    public string? SnmpV3Username { get; set; }

    public string? SnmpV3AuthProtocol { get; set; }

    public string? SnmpV3AuthPassword { get; set; }

    public string? SnmpV3PrivacyProtocol { get; set; }

    public string? SnmpV3PrivacyPassword { get; set; }

    public string? SnmpV3ContextName { get; set; }

    public string? UnifiApiKey { get; set; }

    public string? GenericUsername { get; set; }

    public string? GenericPassword { get; set; }

    public string? GenericToken { get; set; }

    public string? MailSmtpUsername { get; set; }

    public string? MailSmtpPassword { get; set; }

    public string? MailImapUsername { get; set; }

    public string? MailImapPassword { get; set; }

    public string ValuesText { get; set; } = string.Empty;

    public bool IsDeleted { get; set; }
}

public sealed class WorkspaceNotificationRuleEditorInput
{
    public Guid Id { get; set; }

    public string Name { get; set; } = string.Empty;

    public bool Enabled { get; set; } = true;

    public Guid? SenderId { get; set; }

    public Guid? ReceiverId { get; set; }

    public Guid? TargetElementId { get; set; }

    public bool IncludeDescendants { get; set; } = true;

    public List<SensorState> TriggerStates { get; set; } = [];

    public int? CooldownMinutes { get; set; }

    public int? Threshold { get; set; }

    public string SubjectTemplate { get; set; } = NotificationTemplateCatalog.DefaultSubjectTemplate;

    public string TextTemplate { get; set; } = NotificationTemplateCatalog.DefaultTextTemplate;

    public string HtmlTemplate { get; set; } = NotificationTemplateCatalog.DefaultHtmlTemplate;

    public List<SelectListItem> SenderOptions { get; set; } = [];

    public List<SelectListItem> ReceiverOptions { get; set; } = [];

    public List<SelectListItem> TargetOptions { get; set; } = [];

    public List<SelectListItem> TriggerStateOptions { get; set; } = [];
}

public sealed class TemplateApplyInput
{
    public Guid TemplateId { get; set; }

    public Guid? TargetElementId { get; set; }

    public List<SelectListItem> TargetOptions { get; set; } = [];
}

public sealed class EmailNotificationSettingsInput
{
    public string SenderName { get; set; } = string.Empty;

    public string SenderEmail { get; set; } = string.Empty;

    public string SmtpHost { get; set; } = string.Empty;

    public int? SmtpPort { get; set; }

    public bool UseSsl { get; set; } = true;

    public string? Username { get; set; }

    public string? Password { get; set; }
}

public sealed class WebhookNotificationSettingsInput
{
    public string EndpointUrl { get; set; } = string.Empty;

    public string? Secret { get; set; }

    public int? TimeoutSeconds { get; set; }
}
